on:
  push:
    branches:
      - main
 
permissions:
  id-token: write
  contents: read
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
 
      - name: Set environment variable for subscription ID
        run: echo "SUBSCRIPTION_ID=9ec75d1a-60ff-4851-8c9f-dca73c17bcd2" >> $GITHUB_ENV
 
      - name: Set environment variable for resourceGroupName
        run: echo "resourceGroupName=RG-SME-DataPipeline" >> $GITHUB_ENV
 
      - name: List root directory contents
        run: ls -al ${{ github.workspace }}
 
      - name: List adfroot directory contents
        run: ls -al ${{ github.workspace }}/adfroot
 
      - name: Ensure required directories exist
        run: |
          mkdir -p ${{ github.workspace }}/adfroot/{integrationRuntime,pipeline,dataset,linkedService,trigger,dataflow,credential,adfcdc,managedVirtualNetwork}
          ls -al ${{ github.workspace }}/adfroot
 
      - name: Install ADF Utilities package
        run: npm install
        working-directory: ${{ github.workspace }}/adfroot/build
 
      - name: Validate
        run: |
          npm run build validate "${{ github.workspace }}/adfroot/" "/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.resourceGroupName }}/providers/Microsoft.DataFactory/factories/testadf54"
        working-directory: ${{ github.workspace }}/adfroot/build
 
      - name: Validate and Generate ARM template
        run: |
          npm run build export "${{ github.workspace }}/adfroot/" "/subscriptions/${{ env.SUBSCRIPTION_ID }}/resourceGroups/${{ env.resourceGroupName }}/providers/Microsoft.DataFactory/factories/testadf54" "ExportedArmTemplate"
        working-directory: ${{ github.workspace }}/adfroot/build
 
      - name: Verify ARM template files
        run: |
          echo "Checking for ARMTemplateForFactory.json file"
          ls -al ${{ github.workspace }}/adfroot/build/ExportedArmTemplate
          if [ ! -f "${{ github.workspace }}/adfroot/build/ExportedArmTemplate/ARMTemplateForFactory.json" ]; then
            echo "ARMTemplateForFactory.json does not exist!"
            exit 1
          fi
          echo "Checking for ARMTemplateParametersForFactory.json file"
          if [ ! -f "${{ github.workspace }}/adfroot/build/ExportedArmTemplate/ARMTemplateParametersForFactory.json" ]; then
            echo "ARMTemplateParametersForFactory.json does not exist!"
            exit 1
          fi
        working-directory: ${{ github.workspace }}/adfroot/build
 
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ExportedArmTemplate
          path: ${{ github.workspace }}/adfroot/build/ExportedArmTemplate
 
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ExportedArmTemplate
 
      
 
       
 
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
 
    
 
      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: RG-SME-DataPipeline
          dataFactoryName: testadf54
          armTemplateFile: adfroot/build/ARMTemplateForFactory.json
          armTemplateParametersFile: testadf54/ARMTemplateParametersForFactory.json
